{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    app: {{ include "demo.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "demo.name" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
  {{- end }}
